<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260825193828 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the PriceIt schema, or baseline the legacy production schema.';
    }

    public function up(Schema $schema): void
    {
        if ($schema->hasTable('item')) {
            $this->abortIf(
                !$schema->hasTable('media') || !$schema->hasTable('messenger_messages'),
                'The legacy PriceIt schema is incomplete; refusing to record it as the baseline.',
            );

            if (!$schema->getTable('item')->hasColumn('print_requested')) {
                $this->addSql('ALTER TABLE item ADD print_requested BOOLEAN DEFAULT FALSE NOT NULL');
                $this->addSql('ALTER TABLE item ALTER print_requested DROP DEFAULT');
            }

            return;
        }

        $this->addSql('CREATE TABLE item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id VARCHAR(64) NOT NULL, print_requested BOOLEAN NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, price NUMERIC(8, 2) DEFAULT NULL, transcript TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, quickbase_inventory_record_id INT DEFAULT NULL, quickbase_exported_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F1B251E19EB6921 ON item (client_id)');
        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(255) NOT NULL, filename VARCHAR(255) DEFAULT NULL, mime_type VARCHAR(100) DEFAULT NULL, size INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, item_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10C126F525E ON media (item_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C126F525E');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
