<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260925103337 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'mail_event: Brevo webhook calls, for the admin Mail page';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mail_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, name VARCHAR(32) NOT NULL, brevo_event VARCHAR(32) DEFAULT NULL, message_id VARCHAR(255) NOT NULL, suppression BOOLEAN NOT NULL, reason VARCHAR(255) DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payload JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX mail_event_email_idx ON mail_event (email)');
        $this->addSql('CREATE INDEX mail_event_occurred_idx ON mail_event (occurred_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE mail_event');
    }
}
